export const GAME_CONFIG = {
    CANVAS_WIDTH: 320,
    CANVAS_HEIGHT: 480,
    GRAVITY: 0.5,
    FLAP_FORCE: -8,
    PIPE_SPEED: 2,
    PIPE_SPAWN_INTERVAL: 1500,
    PIPE_GAP: 150,
    GROUND_HEIGHT: 100,
    BIRD_WIDTH: 34,
    BIRD_HEIGHT: 24,
    PIPE_WIDTH: 52,
    PIPE_HEIGHT: 320
}; 